github.com:
    users:
        andcor:
            oauth_token: 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
    git_protocol: ssh
    user: andcor
    oauth_token: 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
